# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ko-KR" # 리뷰 언어 한국어로 설정
early_access: true # CodeRabbit 얼리 액세스 기능 활성화

# 리뷰 전반의 톤과 관점 정의
tone_instructions: |
  React/TypeScript 전문가로서 다음 지침을 준수해요:
  - 유지보수성(maintainability), 가독성(readability), 성능(performance), 보안(security)을 중시해요.
  - 친절하고 전문적인 어조를 유지해요.
  - 구체적이고 실행 가능한 피드백을 제공해요.
  - 긍정적인 측면과 개선이 필요한 측면을 모두 언급해요.
  - 코드의 맥락과 목적을 고려해요.

reviews:
  profile: "assertive" # 리뷰 스타일: 엄격(assertive)
  request_changes_workflow: false # 자동으로 Change Request 상태로 전환하지 않음
  high_level_summary: true # PR 전체 요약 생성
  review_status: true # 리뷰 상태 표시
  assess_linked_issues: false # 연결된 이슈 분석 비활성화
  related_prs: false # 관련 PR 탐색 비활성화
  changed_files_summary: true # 변경된 파일 요약 제공
  poem: false # 시(poem) 생성 비활성화

  # 리뷰 대상 파일 필터링 규칙
  path_filters:
    # 포함할 경로
    - "src/**"
    - ".github/**"
    - "package.json"
    - "vite.config.ts"
    - "eslint.config.js"

    # 제외할 경로 (빌드 산출물 및 바이너리 리소스)
    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!pnpm-lock.yaml"

  # 경로별 세부 리뷰 지침
  path_instructions:
    - path: "src/pages/**"
      instructions: |
        pages 레이어 리뷰 시:
        - 페이지 단위 책임(도메인별 화면 구성)을 잘 지키는지 확인
        - UX 흐름과 접근성(a11y)을 고려한 구조인지 점검
        - 공통 UI(shared)와 widgets를 적절히 조합하는지 확인
        - 비즈니스 로직이 과도하게 포함되지 않았는지 검토

    - path: "src/**/ui/**/*.tsx"
      instructions: |
        UI 컴포넌트 파일 리뷰 시:
        - 파일명이 snake-case인지 확인
        - Props 타입명이 '컴포넌트명Props' 형식인지 확인
        - 컴포넌트는 named export 사용을 권장 (팀 가이드 우선)
        - 이벤트 핸들러 함수명이 handle로 시작하는지 확인
        - 접근성(a11y) 준수 여부 점검:
          - aria-* 속성
          - label과 input의 연결
          - 키보드 포커스 이동 가능 여부
        - 성능 관점에서 memo / useMemo / useCallback이
          목적성 있게 사용되었는지 확인 (남용 여부 포함)

    # vanilla-extract 스타일 파일에 대한 구체적인 리뷰 지침
    - path: "src/**/*.css.ts"
      instructions: |
        Vanilla Extract 스타일 파일 리뷰 지침:

        1. 디자인 토큰 사용
        - color, typography, shadow, zIndex 은 반드시 themeVars를 통해 사용
        - 하드코딩된 값(hex, rgb, fontSize, fontWeight 등) 사용 지양

        2. fontStyles 사용 규칙
        - font 스타일은 themeVars.fontStyles만 사용
        - 반드시 스프레드 연산자 형태로 적용
          예: ...themeVars.fontStyles.body_r_16
        - fontSize / lineHeight / fontWeight를 개별 속성으로 작성하지 않음

        3. border / border-radius 규칙
        - rem 단위 사용 금지
        - px 단위로 명시 (디자인 시스템 기준 일관성 유지)

        4. 기타 스타일 가이드
        - recipe / styleVariants를 상태·변형이 있을 때 적절히 사용
        - 중복 스타일은 공통 style로 추출
        - 전역 스타일 남용 금지 (컴포넌트 캡슐화 유지)

    - path: "src/**"
      instructions: |
        공통 코드 리뷰 지침:
        - 모든 컴포넌트는 TypeScript로 작성
        - 프로젝트 전반의 스타일 가이드 및 컨벤션 준수 여부 확인
        - 중복 코드 제거 및 재사용 가능한 구조 제안

        네이밍 규칙:
        - 컴포넌트: PascalCase
        - 폴더명 / 파일명: snake-case
        - 변수 / 함수: camelCase
        - 상수: UPPER_SNAKE_CASE
        - Props 타입: 컴포넌트명 + Props

        import 규칙:
        - @shared, @features, @widgets 등 alias 기반 절대 경로 import 사용 권장
        - 깊은 상대 경로(../../..) 사용은 가독성과 유지보수 측면에서 지양
        - index.ts를 통한 공개 API import 여부 함께 검토

        API 및 훅 네이밍:
        - API 함수는 동사형(get, fetch, post 등)
        - TanStack Query 훅:
          use + 행위 + 대상 + Query/Mutation
          (예: useFetchUserQuery)

        기타 규칙:
        - svg는 ?react 쿼리를 통해 React 컴포넌트로 import
        - 환경 변수는 import.meta.env 사용
        - 문자열 조합 시 템플릿 리터럴 사용 권장

  # 자동 리뷰 설정
  auto_review:
    enabled: true # 자동 리뷰 활성화
    drafts: false # Draft PR은 리뷰하지 않음
    base_branches:
      - "dev"
      - "main"
    ignore_title_keywords: # 제목에 포함되면 리뷰 스킵
      - "[Docs]"
      - "[skip-review]"

  # CodeRabbit의 자동 코드 생성/보완 기능 비활성화
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  # 연동 도구 설정
  tools:
    markdownlint: # Markdown 문서 품질 검사
      enabled: true
    actionlint: # GitHub Actions 워크플로 검사
      enabled: true
    eslint: # ESLint 기반 TS/JS 린팅
      enabled: true
    gitleaks: # 시크릿/보안 취약점 탐지
      enabled: true

# CodeRabbit이 참고할 지식 베이스 설정
knowledge_base:
  web_search:
    enabled: true # 웹 검색 기반 보조 추론 허용
    instructions: |
      웹 검색은 일반적인 React/TypeScript 베스트 프랙티스,
      공식 문서 수준의 참고 자료 확인 용도로만 사용합니다.
      최신 실험적 API나 특정 버전(예: React 19)에 대한
      도입 권장 근거로 사용하지 않습니다.
  code_guidelines:
    enabled: true
    filePatterns:
      - "README.md" # README를 프로젝트 가이드로 활용
