import type { ExperienceCardData } from "./ui/experience-list-container";

export const MOCK_EXPERIENCES: ExperienceCardData[] = [
  {
    id: 1,
    title: "인스타그램 마케팅 캠페인 기획 및 실행",
    type: "INTERNSHIP",
    isDefault: true,
    updatedAt: "2026-01-01",
  },
  {
    id: 2,
    title: "AI 캐릭터 기반 콘텐츠 마케팅 캠페인 운영",
    type: "PROJECT",
    updatedAt: "2026-01-02",
  },
  {
    id: 3,
    title: "CRM 데이터 기반 고객 타겟 마케팅 운영",
    type: "INTERNSHIP",
    updatedAt: "2026-01-03",
  },
  {
    id: 4,
    title: "콘텐츠 IP 구조 분석 및 글로벌 유통 전략 수립",
    type: "PROJECT",
    updatedAt: "2026-01-04",
  },
  {
    id: 5,
    title: "전자제품 상품 기획 및 구매 데이터 분석 리포트 작성",
    type: "PROJECT",
    updatedAt: "2026-01-05",
  },
  {
    id: 6,
    title: "IT 솔루션 제안서 기반 세일즈 마케팅 기획",
    type: "INTERNSHIP",
    updatedAt: "2026-01-06",
  },
  {
    id: 7,
    title: "데이터 분석 입문 과정 수료 및 대시보드 과제 제출",
    type: "EDUCATION",
    updatedAt: "2026-01-07",
  },
  {
    id: 8,
    title: "브랜드 톤앤매너 정립과 카드뉴스 템플릿 제작",
    type: "PROJECT",
    isDefault: true,
    updatedAt: "2026-01-08",
  },
  {
    id: 9,
    title: "검색광고 키워드 확장 및 소재 A/B 테스트 운영",
    type: "INTERNSHIP",
    updatedAt: "2026-01-09",
  },
  {
    id: 10,
    title: "GA4 이벤트 설계 및 전환 퍼널 분석",
    type: "PROJECT",
    updatedAt: "2026-01-10",
  },
  {
    id: 11,
    title: "고객 인터뷰 기반 페르소나 및 JTBD 정리",
    type: "PROJECT",
    updatedAt: "2026-01-11",
  },
  {
    id: 12,
    title: "SQL 심화 교육 수료: 조인/집계/윈도 함수 실습",
    type: "EDUCATION",
    updatedAt: "2026-01-12",
  },
  {
    id: 13,
    title: "커뮤니티 채널 운영 및 참여 지표 개선",
    type: "INTERNSHIP",
    updatedAt: "2026-01-13",
  },
  {
    id: 14,
    title: "랜딩페이지 카피 개선과 전환율 개선 실험",
    type: "PROJECT",
    updatedAt: "2026-01-14",
  },
  {
    id: 15,
    title: "리텐션 향상을 위한 푸시/이메일 메시지 기획",
    type: "INTERNSHIP",
    isDefault: true,
    updatedAt: "2026-01-15",
  },
  {
    id: 16,
    title: "서비스 온보딩 플로우 개선안 기획 및 와이어프레임 제작",
    type: "PROJECT",
    updatedAt: "2026-01-16",
  },
  {
    id: 17,
    title: "경쟁사 벤치마킹 리서치와 포지셔닝 맵 작성",
    type: "PROJECT",
    updatedAt: "2026-01-17",
  },
  {
    id: 18,
    title: "엑셀/스프레드시트 자동화 교육 수료: 피벗/함수 활용",
    type: "EDUCATION",
    updatedAt: "2026-01-18",
  },
  {
    id: 19,
    title: "B2B 리드 수집 폼 개선 및 문의 전환 최적화",
    type: "INTERNSHIP",
    updatedAt: "2026-01-19",
  },
  {
    id: 20,
    title: "SNS 주간 콘텐츠 캘린더 제작 및 운영 프로세스 정리",
    type: "INTERNSHIP",
    updatedAt: "2026-01-20",
  },
  {
    id: 21,
    title: "고객 세그먼트별 메시지 전략 수립과 성과 리포팅",
    type: "PROJECT",
    updatedAt: "2026-01-21",
  },
  {
    id: 22,
    title: "프로모션 쿠폰 정책 설계 및 유입 경로별 효과 분석",
    type: "PROJECT",
    isDefault: true,
    updatedAt: "2026-01-22",
  },
  {
    id: 23,
    title: "서비스 소개서(원페이저) 제작 및 세일즈 키트 구성",
    type: "INTERNSHIP",
    updatedAt: "2026-01-23",
  },
  {
    id: 24,
    title: "Figma UI 디자인 기초 교육 수료 및 컴포넌트 실습",
    type: "EDUCATION",
    updatedAt: "2026-01-24",
  },
  {
    id: 25,
    title: "카카오 채널 메시지 운영 및 클릭률 개선 실험",
    type: "INTERNSHIP",
    updatedAt: "2026-01-25",
  },
  {
    id: 26,
    title: "리뷰 데이터 텍스트 마이닝으로 핵심 불만 요인 도출",
    type: "PROJECT",
    updatedAt: "2026-01-26",
  },
  {
    id: 27,
    title: "제품 상세페이지 구성 개선 및 구매 전환 요소 정리",
    type: "PROJECT",
    updatedAt: "2026-01-27",
  },
  {
    id: 28,
    title: "마케팅 KPI 설계 교육 수료: CAC/LTV/ROAS 이해",
    type: "EDUCATION",
    updatedAt: "2026-01-28",
  },
  {
    id: 29,
    title: "브랜드 협업 제안서 작성 및 파트너 커뮤니케이션",
    type: "INTERNSHIP",
    isDefault: true,
    updatedAt: "2026-01-29",
  },
  {
    id: 30,
    title: "앱스토어 최적화(ASO) 키워드 리서치 및 문구 개선",
    type: "PROJECT",
    updatedAt: "2026-01-30",
  },
  {
    id: 31,
    title: "고객 문의 태깅 체계 정비 및 FAQ 고도화",
    type: "INTERNSHIP",
    updatedAt: "2026-01-31",
  },
  {
    id: 32,
    title: "React 실습 교육 수료: 컴포넌트/상태관리 과제 완성",
    type: "EDUCATION",
    updatedAt: "2026-02-01",
  },
  {
    id: 33,
    title: "유튜브 숏폼 콘텐츠 기획 및 업로드 운영",
    type: "INTERNSHIP",
    updatedAt: "2026-02-02",
  },
  {
    id: 34,
    title: "콘텐츠 성과 분석 리포트 템플릿 제작 및 정례화",
    type: "PROJECT",
    updatedAt: "2026-02-03",
  },
  {
    id: 35,
    title: "이벤트 페이지 트래픽 모니터링 및 이탈 구간 개선",
    type: "PROJECT",
    updatedAt: "2026-02-04",
  },
  {
    id: 36,
    title: "유입 채널별 예산 배분안 수립 및 성과 비교",
    type: "PROJECT",
    isDefault: true,
    updatedAt: "2026-02-05",
  },
  {
    id: 37,
    title: "B2B 뉴스레터 발행 운영 및 오픈율 개선",
    type: "INTERNSHIP",
    updatedAt: "2026-02-06",
  },
  {
    id: 38,
    title: "세일즈 콜 노트 정리 및 고객 니즈 유형화",
    type: "INTERNSHIP",
    updatedAt: "2026-02-07",
  },
  {
    id: 39,
    title: "데이터 시각화 교육 수료: 차트 선택과 스토리텔링 실습",
    type: "EDUCATION",
    updatedAt: "2026-02-08",
  },
  {
    id: 40,
    title: "서비스 가격 정책 비교 분석 및 패키지 구성 제안",
    type: "PROJECT",
    updatedAt: "2026-02-09",
  },
  {
    id: 41,
    title: "프로덕트 릴리즈 노트 작성 및 공지 채널 운영",
    type: "INTERNSHIP",
    updatedAt: "2026-02-10",
  },
  {
    id: 42,
    title: "신규 기능 소개 영상 스크립트 작성 및 촬영 기획",
    type: "PROJECT",
    updatedAt: "2026-02-11",
  },
  {
    id: 43,
    title: "고객 재방문 유도 캠페인 시나리오 설계",
    type: "PROJECT",
    isDefault: true,
    updatedAt: "2026-02-12",
  },
  {
    id: 44,
    title: "AARRR 퍼널 기반 지표 정의 및 개선 과제 도출",
    type: "PROJECT",
    updatedAt: "2026-02-13",
  },
  {
    id: 45,
    title: "인플루언서 리스트업 및 협업 조건 정리",
    type: "INTERNSHIP",
    updatedAt: "2026-02-14",
  },
  {
    id: 46,
    title: "리퍼럴 프로그램 구조 설계 및 참여 흐름 개선",
    type: "PROJECT",
    updatedAt: "2026-02-15",
  },
  {
    id: 47,
    title: "고객 설문 설계 및 결과 분석 리포트 작성",
    type: "PROJECT",
    updatedAt: "2026-02-16",
  },
  {
    id: 48,
    title: "디자인 시스템 기초 교육 수료 및 토큰 정리 실습",
    type: "EDUCATION",
    updatedAt: "2026-02-17",
  },
  {
    id: 49,
    title: "CRM 캠페인 운영: 세그먼트별 발송 일정 관리",
    type: "INTERNSHIP",
    updatedAt: "2026-02-18",
  },
  {
    id: 50,
    title: "브랜드 슬로건/핵심 메시지 정리 및 문구 가이드 제작",
    type: "PROJECT",
    isDefault: true,
    updatedAt: "2026-02-19",
  },
  {
    id: 51,
    title: "시장 규모 및 타깃 고객군 정의 리서치",
    type: "PROJECT",
    updatedAt: "2026-02-20",
  },
  {
    id: 52,
    title: "프로젝트 관리 교육 수료: 일정/리스크/이슈 트래킹 실습",
    type: "EDUCATION",
    updatedAt: "2026-02-21",
  },
  {
    id: 53,
    title: "퍼포먼스 광고 소재 제작 요청서 작성 및 운영 핸드오프",
    type: "INTERNSHIP",
    updatedAt: "2026-02-22",
  },
  {
    id: 54,
    title: "고객 여정맵 작성 및 핵심 접점 개선 아이디어 도출",
    type: "PROJECT",
    updatedAt: "2026-02-23",
  },
  {
    id: 55,
    title: "바이럴 콘텐츠 기획안 작성 및 게시 일정 운영",
    type: "INTERNSHIP",
    updatedAt: "2026-02-24",
  },
  {
    id: 56,
    title: "구매/결제 단계 이탈 원인 분석 및 개선안 제시",
    type: "PROJECT",
    updatedAt: "2026-02-25",
  },
  {
    id: 57,
    title: "신규 고객 온보딩 가이드 문서 작성 및 개선",
    type: "INTERNSHIP",
    isDefault: true,
    updatedAt: "2026-02-26",
  },
  {
    id: 58,
    title: "서비스 소개 랜딩페이지 구조 개편 및 섹션 구성안 작성",
    type: "PROJECT",
    updatedAt: "2026-02-27",
  },
  {
    id: 59,
    title: "교육 과정 수료: 데이터 기반 마케팅 실습 프로젝트 완성",
    type: "EDUCATION",
    updatedAt: "2026-02-28",
  },
  {
    id: 60,
    title: "고객 피드백 분류 체계 개선 및 우선순위 기준 수립",
    type: "PROJECT",
    updatedAt: "2026-03-01",
  },
  {
    id: 61,
    title: "브랜드 공식 블로그 운영 및 SEO 기본 최적화 적용",
    type: "INTERNSHIP",
    updatedAt: "2026-03-02",
  },
  {
    id: 62,
    title: "세일즈 파이프라인 단계 정의 및 리드 상태값 정리",
    type: "INTERNSHIP",
    updatedAt: "2026-03-03",
  },
  {
    id: 63,
    title: "가격/혜택 비교표 제작 및 고객 설득 포인트 정리",
    type: "PROJECT",
    updatedAt: "2026-03-04",
  },
  {
    id: 64,
    title: "서비스 소개 자료 한글/영문 버전 제작 및 배포",
    type: "PROJECT",
    isDefault: true,
    updatedAt: "2026-03-05",
  },
  {
    id: 65,
    title: "신규 콘텐츠 시리즈 기획 및 제작 파이프라인 정리",
    type: "INTERNSHIP",
    updatedAt: "2026-03-06",
  },
  {
    id: 66,
    title: "고객 코호트 분석으로 재구매 패턴 도출",
    type: "PROJECT",
    updatedAt: "2026-03-07",
  },
  {
    id: 67,
    title: "커뮤니케이션 교육 수료: 회의록/요청사항 정리 실습",
    type: "EDUCATION",
    updatedAt: "2026-03-08",
  },
  {
    id: 68,
    title: "신규 기능 베타 모집 캠페인 기획 및 참여율 개선",
    type: "PROJECT",
    updatedAt: "2026-03-09",
  },
  {
    id: 69,
    title: "스토어 이벤트 배너 제작 및 노출 위치별 성과 비교",
    type: "INTERNSHIP",
    updatedAt: "2026-03-10",
  },
  {
    id: 70,
    title: "사용자 행동 로그 기반 주요 클릭 흐름 분석",
    type: "PROJECT",
    updatedAt: "2026-03-11",
  },
  {
    id: 71,
    title: "제품 기획 교육 수료: 문제정의-가설-실험 설계 과제 제출",
    type: "EDUCATION",
    isDefault: true,
    updatedAt: "2026-03-12",
  },
  {
    id: 72,
    title: "고객 세그먼트 리포트 제작 및 타깃별 추천 전략 정리",
    type: "PROJECT",
    updatedAt: "2026-03-13",
  },
  {
    id: 73,
    title: "파트너사 공동 프로모션 운영 및 정산 자료 정리",
    type: "INTERNSHIP",
    updatedAt: "2026-03-14",
  },
  {
    id: 74,
    title: "고객 불만 사례 분석 및 개선 우선순위 로드맵 제안",
    type: "PROJECT",
    updatedAt: "2026-03-15",
  },
  {
    id: 75,
    title: "데이터 리터러시 교육 수료: 지표 해석과 실무 적용",
    type: "EDUCATION",
    updatedAt: "2026-03-16",
  },
  {
    id: 76,
    title: "브랜드 이벤트 운영 매뉴얼 작성 및 체크리스트 정리",
    type: "INTERNSHIP",
    updatedAt: "2026-03-17",
  },
  {
    id: 77,
    title: "콘텐츠 성과 대시보드 정리 및 주간 리포트 자동화 설계",
    type: "PROJECT",
    updatedAt: "2026-03-18",
  },
  {
    id: 78,
    title: "고객 재구매 유도 캠페인 시나리오 개선 및 문구 테스트",
    type: "INTERNSHIP",
    isDefault: true,
    updatedAt: "2026-03-19",
  },
  {
    id: 79,
    title: "수업/교육 프로젝트: 데이터로 보는 소비자 트렌드 분석 보고서",
    type: "EDUCATION",
    updatedAt: "2026-03-20",
  },
  {
    id: 80,
    title: "신규 서비스 런칭 전후 성과 비교 및 인사이트 정리",
    type: "PROJECT",
    updatedAt: "2026-03-21",
  },
];
